apiVersion: batch/v1
kind: Job
metadata:
  name: training
  namespace: sugiyama-demo
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: get-code
        image: alpine/git
        command:
        - git
        - clone
        - https://github.com/IMOKURI/image-competition-baseline.git
        - /working
        volumeMounts:
        - mountPath: /working
          name: working
      containers:
      - name: training
        image: quay.io/yoshio_sugiyama/torch-image-baseline:1.9.0
        command:
        - python
        - train.py
        resources:
          limits:
            nvidia.com/gpu: 8
        env:
          # - name: CUDA_VISIBLE_DEVICES
          #   value: "0:0,1:1,2:2,3:0"
          - name: XDG_CACHE_HOME
            value: /app/cache/.cache
          - name: XDG_CONFIG_HOME
            value: /app/cache/.config
          - name: http_proxy
            value: ""
          - name: https_proxy
            value: ""
        volumeMounts:
        - mountPath: /app/inputs
          name: nfs
          subPath: cassava/inputs
        - mountPath: /app/outputs
          name: nfs
          subPath: cassava/outputs
        - mountPath: /app/cache
          name: nfs
          subPath: cassava/cache
        - mountPath: /app/working
          name: working
        - mountPath: /dev/shm
          name: shm
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: pvc-sv1
      - name: working
        # emptyDir: {}
        emptyDir:
          medium: Memory
      - name: shm
        emptyDir:
          medium: Memory
      # nodeSelector:
      #   nvidia.com/gpu.product: NVIDIA-A100-SXM4-40GB-MIG-3g.20gb

