apiVersion: batch/v1
kind: Job
metadata:
  name: training
  namespace: sugiyama-demo
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: get-code
        image: alpine/git
        command:
        - git
        - clone
        - https://github.com/IMOKURI/image-competition-baseline.git
        - /working
        volumeMounts:
        - mountPath: /working
          name: working
      containers:
      - name: training
        image: quay.io/yoshio_sugiyama/torch-image-baseline:1.9.0
        command:
        - python
        - train.py
        resources:
          limits:
            nvidia.com/gpu: 1
        env:
          - name: XDG_CACHE_HOME
            value: /app/cache/.cache
          - name: XDG_CONFIG_HOME
            value: /app/cache/.config
          - name: http_proxy
            value: ""
          - name: https_proxy
            value: ""
        volumeMounts:
        - mountPath: /app/inputs
          name: inputs
          subPath: cassava/inputs
        - mountPath: /app/working
          name: working
        - mountPath: /app/outputs
          name: outputs
        - mountPath: /app/cache
          name: cache
      volumes:
      - name: inputs
        persistentVolumeClaim:
          claimName: pvc-sv1
      - name: working
        emptyDir: {}
      - name: outputs
        emptyDir: {}
      - name: cache
        emptyDir: {}

